Update PlatformIOLibary.yaml

diff --git a/.github/workflows/PlatformIOLibary.yaml b/.github/workflows/PlatformIOLibary.yaml
--- a/.github/workflows/PlatformIOLibary.yaml
+++ b/.github/workflows/PlatformIOLibary.yaml
@@ -69,9 +69,13 @@ jobs:
     runs-on: ubuntu-latest
     needs: [setup]
     steps:
-      - if: needs.setup.outputs.up_version  == 'true' || needs.setup.outputs.pullrequest  == 'false'
+      - if: needs.setup.outputs.up_version  == 'true'
         run: |
           echo "::error file=library.json::Version not correct"
+          exit 1
+      - if: needs.setup.outputs.pullrequest  == 'false'
+        run: |
+          echo "::error file=library.json::Not a Pull Request"
           exit 1
       - uses: actions/checkout@v2
       - name: Cache pip
